### ISSUE TITLE
Update for V3

### ISSUE THREAD

**Issue by austriker27** [bryantgillespie/alfred-statamic-docs#1]
Hello! 

This workflow is amazing but I'd love if it were updated for Statamic 3. 

Statamic 3 docs:

I don't know PHP nor have ever built a Alfred workflow but I reckon it should be as easy as removing the `v2` from the subdomain URL search (inside this [file](https://github.com/bryantgillespie/alfred-statamic-docs/blob/4ee6ff751291815a038cec699fbee991aad7b7f9/vendor/algolia/algoliasearch-client-php/resources/ca-bundle.crt)?). Maybe? 

I'd be happy to open a PR to help if it's something I can do.

**Comment by bryantgillespie** [comment]
Great idea. I'll see what I can do.

**Comment by bryantgillespie** [comment]
@austriker27 
Try this out.
https://github.com/bryantgillespie/alfred-statamic-docs/releases/tag/2.0

**Comment by austriker27** [comment]
> @austriker27
> Try this out.
> https://github.com/bryantgillespie/alfred-statamic-docs/releases/tag/2.0

Perfect! It works great! Thanks so much, this workflow is amazing.
