### ISSUE TITLE
Can't import

### ISSUE THREAD

**Issue by edalzell** [bryantgillespie/alfred-statamic-docs#3]
Trying your latest v3 version and I can't import it
<img width="890" alt="image" src="https://user-images.githubusercontent.com/6069653/95771968-d71ffb80-0c70-11eb-9447-02c2ea98eda0.png">

**Comment by bryantgillespie** [comment]
That's weird @edalzell.

Not really sure how to troubleshoot this.

I removed the workflow and tried reinstalling myself - and it's working ok.

You downloaded the file from this link?
https://github.com/bryantgillespie/alfred-statamic-docs/releases/download/2.0/Statamic.Docs.alfredworkflow

Maybe an Alfred version issue?
I'm on 4.1.1.

<img width="757" alt="Screen Shot 2020-10-12 at 1 11 53 PM" src="https://user-images.githubusercontent.com/23302570/95773489-933aef80-0c8c-11eb-8da8-337eb77e9c5e.png">

**Comment by edalzell** [comment]
Maybe I downloaded the wrong version? The one from the above linked worked. Thanks.
