### ISSUE TITLE
Broken Since Recent Website Redesign

### ISSUE THREAD

**Issue by intrepidws** [bryantgillespie/alfred-statamic-docs#4]
My best guess is that the Algolia index name changed. While I know how to grab the Algolia App ID and key (which both remain the same as what you're using in this package) using Chrome Dev Tools, I don't know of a similar way to determine the name of the index that they are using. Maybe you know of a way?

**Comment by bryantgillespie** [comment]
Thanks for the heads up. Will take a look and get it fixed this shortly.

**Comment by intrepidws** [comment]
I'd love to know how you find the index name, as I maintain a similar package for another framework. I had to guess the index name for that :)

**Comment by bryantgillespie** [comment]
I don't think this was an issue with the index name, ids, keys etc.

Are you on Monterey?

Think it has something to do with PHP not being installed automatically on Monterey. I scoped the https://github.com/clnt/alfred-tailwindcss-docs repo and it mentions something about that.

Just forked the latest version they had there and swapped index name, app id, and key.

Will have a new version up soon.

> I'd love to know how you find the index name, as I maintain a similar package for another framework. I had to guess the index name for that :)

The index name should be in the requests getting sent to Algolia.
https://www.loom.com/share/c35a20bb891e46d588a3e5fb999bb897

**Comment by bryantgillespie** [comment]
Closed with #5

**Comment by intrepidws** [comment]
I am on Monterey and I think my switch was closely timed with the new Statamic docs website, so I wrongly assumed that was the problem. Thanks for updating everything - I use this often and it's great to have it back and working.

> The index name should be in the requests getting sent to Algolia. https://www.loom.com/share/c35a20bb891e46d588a3e5fb999bb897

Oh wow, that's simple huh. I was looking in the Headers tab and had never clicked into the Payload tab. Thanks for the explanation, I appreciate it.

**Comment by bryantgillespie** [comment]
Yeah no worries. I haven't built any sites in Statamic over the last couple months so I wasn't aware it was broken.
